duplicate-post-admin.php, duplicate-post-options.php
HI
I created this pull requewst to fixed issue mention here 
https://github.com/enricobattocchi/duplicate-post/issues/1. Thank you.
=> Implement Yoda Condition, Fix strict comparison issue.

duplicate-post-admin.php
=> Add missing gettext to Subscribe button

duplicate-post-admin.php
* Option for `Clone` is added to the Bulk Actions dropdown checking only if the current post type is enabled in the Settings. We should also check if the current user is allowed to perform the clone operation.
*  Checks for user permissions before registering the bulk action for cloning items.
* The function hooked to `admin_init` has been renamed from `duplicate_post_add_bulk_filters_for_enabled_post_types` to `duplicate_post_add_bulk_filters` to signify the checks are not only on the current post type.
1. Visit `Settings`→`Duplicate Post`, second tab `Permissions` to see if at least a role is not allowed to copy items (by default Author and Contributors)
2. Also look at which post …
=> Check user permission for bulk actions, rename function

compat/duplicate-post-wpml.php, duplicate-post-admin.php, duplicate-post-common.php, duplicate-post-options.php
* No precision alignment (WPCS rule).
* No inline tabs.
* Exactly one newline at the end of a file.
* No space between unary plus/minus and increment operators and the variable/number these apply to.
... which _may_ prevent "headers already send errors"  for the whitespace after the close tag.
* _N/A_
=> CS: various minor fixes

duplicate-post-admin.php
* Code documentation.
* Code documentation.
*
* _N/A_ This is a documentation only change.
=> Docs: minor comment punctuation fixes

src/admin/views/options.php
* See https://yoast.atlassian.net/browse/QAK-2570
* Extends the permission settings warning text to include the new rewrite and republish feature
*
* See https://yoast.atlassian.net/browse/QAK-2570
*
*
Fixes #
=> [QAK-2570] Extend warning text to include rewrite and republish

src/ui/class-post-list.php
* This PR optimizes the query used to filter out Rewrite and Republish posts when Elementor is active and fixes the post count.
* This PR optimizes the query used to filter out Rewrite and Republish posts when Elementor is active and fixes the post count.
*
* Install Elementor, do not activate it yet
* Create a number of R&R copies from existing posts, do not republish them
* See that you can see them in the post list
* Activate Elementor
* See that you can't see any Rewrite & Republish copy in the post list _and_ that the total post counts are correct.
*
This PR affects the following parts of the plugin, which may require …
=> Optimized the query and fixed post count

.editorconfig, .gitattributes
* We want to share basic code formatting rules across the development team.
* Introduces a .editorconfig file for unifying the coding style for different editors and IDEs.
*
- Switch to this branch.
- Close and reopen your editor / IDEs, just in case.
- Your editor / IDEs should now be able to pick up the formatting rules in the .editorconfig file.
- Check if your editor / IDEs has any related setting to configure: some editors support editorconfig natively, others need a plugin to be installed, see https://editorconfig.org/#download
- Create a new php file e.g. `touch test.php`
- Open it in your editor / IDE.
- Write some random string, create a new line and press the …
=> P3-324 Add editorconfig file

tests/class-post-republisher-test.php, tests/handlers/class-check-changes-handler-test.php, tests/ui/class-row-actions-test.php
=> CS: order use statements alphabetically

src/class-permissions-helper.php
* Code quality
* Code quality
* _N/A_
=> QA: remove a redundant condition block

duplicate-post-admin.php
* Code quality
* Code quality
No need to assign the return value of a function call to a variable, if all that's being done with it is to `return` it.
* _N/A_
=> QA: remove redundant variable assignment

tests/ui/class-block-editor-test.php
* Code quality
* Code quality
Variables which are not used, do not need to be declared.
* _N/A_
=> QA: remove unused variables

compat/duplicate-post-gutenberg.php, compat/duplicate-post-jetpack.php, compat/duplicate-post-wpml.php, duplicate-post-admin.php, duplicate-post-common.php, duplicate-post.php, tests/bootstrap.php
Docs: fix up the remaining `@package` tags to be consistent.
Includes alignment of tag content of tags in tag blocks.
* _N/A_
=> Docs: fix up the remaining `@package` tags

src/admin/views/options.php
Add a missing namespace to a "view"  file.
While the file does not introduce any symbols in the global namespace, it is without the `src` directory and there is nothing stopping us from namespacing it.
Includes:
* Using FQN function calls for the few which didn't so far.
* Removing the file docblock.
* Check out this branch.
* Open the admin options page of the plugin.
* Verify there are no PHP errors in the logs and that the page displays correctly as expected.
=> QA: add missing namespace

src/ui/class-column.php
=> CS: minor clean up after merges

admin-functions.php
* Code quality
* Code quality
The `Utils` class also contains a `addslashes_to_strings_only()` method, which does exactly the same.
To reduce duplicate code and the associated maintenance overhead, that method is now called under the hood.
* Check out this branch.
* Go to the admin interface and do something which would cause post_meta data and/or comments to be copied.
* There should be no error messages in the logs and the functionality should work same as before.
=> QA: remove duplicate code

tests/admin/options-page-test.php
* Improve tests
* Improve tests
Rename a test to better describe what is being tested.
* _N/A_ If the tests pass, we're good.
=> QA: rename test

composer.json
* needed for publishing on packagist
* needed for publishing on packagist
*
*
*
*
Fixes #
=> add wordpress plugin part to composer.json

composer.json
* add config to composer.json need for packagist
* add config to composer.json need for packagist
*
*
*
*
Fixes #
=> Composer wp plugin

duplicate-post.php
* We want to port changes from #182 direclty on master so they can be used on packagist.
* Fixes a bug where the plugin would not initialize if installed via composer.
*
* Already tested on #182 
*
*
Fixes #181
=> Fix composer initialize on master

composer.json
* Update dev tools
* Update dev tools
Refs:
* https://github.com/Yoast/wp-test-utils/releases/
* _N/A_ if the build passes, we're good
=> Composer: update to WP Test Utils 1.0.0

composer.json
* Updated dependency
* Updated dependency
Updated non-dev dependency:
* Composer Installers from 1.9.0 to 1.12.0
Refs:
* https://github.com/composer/installers/releases/tag/v1.12.0
* https://github.com/composer/installers/releases/tag/v1.11.0
* https://github.com/composer/installers/releases/tag/v1.10.0
* _N/A_
=> Composer: update installer package

src/ui/newsletter.php, tests/post-republisher-test.php, tests/ui/classic-editor-test.php
* Use FQN function calls in namespaced files.
* `null` must be the last type in a docblock type declaration.
=> CS: various minor cleanup

readme.txt
* WP 5.9 will be released on Jan 25, the same day as the 4.4 release.
* Sets the WordPress tested up to version to 5.9.
*
*
*
*
Fixes #
=> Sets the WordPress tested up to version to 5.9.

src/ui/newsletter.php, tests/ui/classic-editor-test.php
*
* _N/A_ These changes have no impact on functionality.
=> CS: minor fixes

.github/workflows/deploy.yml
* Update CI
* Update CI
The `setup-node` action has released a new major.
This upgrades the deploy workflow to use this new action runner.
Ref: https://github.com/actions/setup-node/releases/tag/v3.0.0
* _N/A_ If the build passes (and the deploy after the merge succeeds), we're good.
=> GH Actions: update setup-node action runner

package.json, yarn.lock
* update grunt-plugin-tasks to 2.3 neede for jenkins release task
* update grunt-plugin-tasks to 2.3
*
*
*
*
Fixes #
=> update grunt-plugin-tasks to 2.3

readme.txt
* We want to bump the "tested up" WP version
* Sets the WordPress tested up to version to 6.0.
*
*
*
*
Fixes #
=> Set tested up to WP 6.0

readme.txt
*
* Sets the minimum supported WordPress version to 5.9.
*
*
*
*
Fixes [PC-340]
[PC-340]: https://yoast.atlassian.net/browse/PC-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set minimum WP version to 5.9

.github/workflows/deploy.yml
* CI maintenance
* CI maintenance
Ensure that `coverage: none` is always used (except for when running Coverage) as it prevents problems with undesired extensions being installed/incorrectly configured.
=> GH Actions: minor tweak

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
*
* Prepares the repo for the rename of master to main.
*
*
*
*
Fixes #
=> Rename relevant master references to main

.github/workflows/deploy.yml, README.md
* prepaire for moving master to main on yoast-dist
* prepaire for moving master to main on yoast-dist
*
*
*
*
Fixes #
=> preparre for rename masin to master yoast-dist

readme.txt
* Sets tested up to version to 6.1
* Sets tested up to version to 6.1
*
* N/A
*
*
Fixes #
=> Set tested up to version to 6.1

admin-functions.php
*
* Remove call to deprecated duplicate_post_blacklist_filter filter.
*
* -
*
*
Fixes [PC-453](https://yoast.atlassian.net/browse/PC-453)
=> Remove call to deprecated duplicate_post_blacklist_filter filter

composer.json
* Update dev dependencies
* Update dev dependencies
Refs:
* https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/1.0.4
* https://github.com/Yoast/wp-test-utils/releases/tag/1.1.0
* _N/A_ If the tests pass, we're good.
=> Composer: update test utilities

.github/workflows/test.yml
* CI maintenance
* CI maintenance
Turn on the tests for PHP 8.2 and as the tests currently pass without issue, don't allow the build to fail.
* _N/A_
=> GH Actions: run the tests against PHP 8.2

readme.txt
* Sets the minimum supported WordPress version to 6.0.
* Sets the minimum supported WordPress version to 6.0.
*
*
*
*
Fixes #
=> Set minimum WP version to 6.0

duplicate-post.php, readme.txt
*
* Sets the minimum supported WordPress version to 6.1.
*
* N/A
* N/A
*
Fixes #
=> Set the minimum supported WordPress version to 6.1

readme.txt
*
* Sets the WordPress tested up to version to 6.3.
*
*
*
*
Fixes #
=> Set the WordPress tested up to version to 6.3

duplicate-post.php, readme.txt
*
* Set the minimum supported WordPress version to 6.3.
*
*
*
*
Fixes #
=> Set the minimum supported WordPress version to 6.2

phpunit.xml.dist
* Dev-only file update
* Dev-only file update
... to the minimum PHPUnit version which is currently in use.
The configuration has also been validates against the schema and where needed, updated.
* _N/A_
=> PHPUnit config: update schema reference

.phpcs.xml.dist
* Minor CS tweak after introduction WP tests.
* Minor CS tweak after introduction WP tests.
Follow up on PR #313
* _N/A_
=> PHPCS: minor tweak

.github/workflows/test.yml
* CI build tweak
* CI build tweak
Follow up on #313
* _N/A_
=> GH Actions: only run "coveralls finished" once all tests have finished running

.github/workflows/test.yml
* CI: fix build
* CI: fix build
Oops.. made a typo in #326. My bad.
* _N/A_
=> GH Actions: fix typo

readme.txt
*
* Sets the WordPress tested up to version to 6.4.
*
*
*
*
Fixes #
=> Set the WordPress tested up to version to 6.4

.github/workflows/cs.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml, .github/workflows/test.yml
* QA
* QA
Update a few links in inline comments as the old URLs are no longer valid.
* _N/A_
=> GH Actions: update a few links in inline comments

admin-functions.php
* "Do not copy these fields" is not working properly, so I will fix it.
* Fixes the regular expression in duplicate_post_copy_post_meta_info function. Props to @ikuno9233.
*
* Create a post with custom fields "test_field_1" and "test_field_2" (original post)
* Make sure that the "Do not copy these fields" setting ensures that the posts cloned from the original post have custom fields as shown in the table below.
| No. | Settings             | test_field_1   | test_field_2   |
|-----|----------------------|----------------|----------------|
| 1   | test_field_1,other*  | Does not exist | Exists         |
| 2   | test_field_2,other*  | Exists         | Does not exist |
| 3 …
=> "Do not copy these fields" is not working properly.

src/ui/newsletter.php, tests/Unit/Admin/Options_Form_Generator_Test.php, tests/Unit/Admin/Options_Inputs_Test.php, tests/WP/Post_Duplicator_Test.php, tests/WP/bootstrap.php
=> CS: minor tweaks to comply with YoastCS 3.0

tests/Unit/Admin/Options_Form_Generator_Test.php, tests/Unit/Admin/Options_Inputs_Test.php, tests/Unit/Admin/Options_Page_Test.php, tests/Unit/Admin/Options_Test.php, tests/Unit/Handlers/Check_Changes_Handler_Test.php, tests/Unit/Permissions_Helper_Test.php, tests/Unit/Post_Duplicator_Test.php, tests/Unit/Post_Republisher_Test.php, tests/Unit/Revisions_Migrator_Test.php, tests/Unit/UI/Admin_Bar_Test.php, tests/Unit/UI/Asset_Manager_Test.php, tests/Unit/UI/Block_Editor_Test.php, tests/Unit/UI/Bulk_Actions_Test.php, tests/Unit/UI/Classic_Editor_Test.php, tests/Unit/UI/Column_Test.php, tests/Unit/UI/Link_Builder_Test.php, tests/Unit/UI/Metabox_Test.php, tests/Unit/UI/Post_States_Test.php, tests/Unit/UI/Row_Actions_Test.php, tests/Unit/Utils_Test.php, tests/Unit/Watchers/Bulk_Actions_Watcher_Test.php, tests/Unit/Watchers/Copied_Post_Watcher_Test.php, tests/Unit/Watchers/Link_Actions_Watcher_Test.php, tests/Unit/Watchers/Original_Post_Watcher_Test.php, tests/Unit/Watchers/Republished_Post_Watcher_Test.php, tests/WP/Post_Duplicator_Test.php
=> Tests: make all classes either abstract or final

admin-functions.php
=> CS/QA: use WP alternative for some native PHP functions

duplicate-post.php, readme.txt
*
* Sets the minimum supported WordPress version to 6.3.
*
*
*
*
Fixes #
=> Sets the minimum supported WordPress version to 6.3.

readme.txt
*
* Sets the WordPress tested up to version to 6.5.
*
*
*
*
Fixes #
=> Sets the WordPress tested up to version to 6.5

duplicate-post.php, readme.txt
*
* Sets the minimum supported WordPress version to 6.4.
*
* NA
*
*
Fixes #
=> Sets the minimum supported WordPress version to 6.4.

readme.txt
*
* Sets the _WordPress tested up to_ version to 6.6.
*
*
*
*
Fixes #
=> Sets the WordPress tested up to version to 6.6

README.md
* Fixes Developer Guide link as it lead to a "Page Not Found"
* Fixes the Developer Guide link that was leading to a non-existent page. Props to @masteradhoc.
* none
* check readme file
* NA
*
Fixes #
=> fix developer guide link

duplicate-post.php, readme.txt
*
* Sets the minimum supported WordPress version to 6.5.
*
*
*
*
Fixes https://github.com/Yoast/wordpress-seo/issues/21664
=> Sets the minimum supported WordPress version to 6.5

.github/workflows/cs.yml, .github/workflows/deploy.yml
* Improve CI
* Improve CI
This job checks the GH Actions workflows against syntax errors and other problems.
Includes minor fixes to pre-existing workflows to allow the build to pass.
* _N/A_ This PR is the test.
=> GH Actions: add actionlint job

duplicate-post.php, readme.txt
*
* Sets the minimum supported WordPress version to 6.6.
*
* NA
*
*
Fixes #
=> Set the minimum supported WordPress version to 6.6

composer.json
* Normalize Composer config
* Normalize Composer config
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
* _N/A_
=> Composer: normalize the file

readme.txt
*
* Sets the _WordPress tested up to_ version to 6.8.
*
*
*
*
Fixes #
=> Sets the WordPress tested up to version to 6.8
