Yoast/duplicate-post

package.json

The `git+` part is not necessary.

Fix the scheme in the repo URL

---

duplicate-post-admin.php
duplicate-post-options.php

Here are two commits which fix errors that are returned by [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) if you run it against the [Automattic](https://github.com/Automattic/VIP-Coding-Standards) and [WordPress](https://github.com/WordPress/WordPress-Coding-Standards) coding standards.
The first one (moving the `exit()` around) has no security benefit, but it makes running this security tool easier. The code duplication is a little unfortunate, but it makes it possible to continue to use this useful heuristic without whitelisting anything.
The second (incorrect escaping function) could potentially lead to a vulnerability.

Fix phpcs errors

---

.gitignore
duplicate-post-options.php
duplicate-post.php

This PR seeks to improve accessibility on the plugin Settings pages:
Note: needs to be rebased onto the `svntrunk` branch
- associates `<label>` elements with all form controls via for/id attributes
- groups checkboxes in `<fieldset>` elements with a visually hidden `<legend>` element
- adds `aria-describedby` attributes to associate some descriptions to their form fields
- adds aria-expanded to the button to toggle private taxonomies visibility
- also, this was a link with a `href="#"` attribute and now it's a button
- minor CSS improvements
- improves the "Settings" link on the Plugins overview page 
- git-ignores the `/vendor/` directory 
- note that my editor automatically removes trailing spaces so you will find unrelated changes to some lines, for a good reason 
Note: the 3 tabs …

Settings pages accessibility first run

---

duplicate-post-admin.php
duplicate-post-common.php

In this PR:
Note: needs to be rebased onto the `svntrunk` branch.
- improved the row-action links in the Posts and Pages overview by adding `aria-label` attributes
- removed redundant `title` attributes 
- post with no post title should stay with no title when cloned (please double check this)
- made sure to use the WordPress default string "(no title)" instead of "Untitled" 
- removed the legacy CSS class `updated` in favor of `notice notice-success`
- in the Posts / Pages overview pages, make sure the "Clone" and "New Draft" row action links do have `aria-label` attributes that contain the post title
- create a post with no title
- clone the post
- observe the cloned post is still with no title
- keep in mind WordPress adds a `(no title)` string in the Posts overview, but that's only …

Second round of accessibility improvements.

---

duplicate-post-admin.php
duplicate-post-common.php
duplicate-post-options.css
duplicate-post-options.php
duplicate-post.css
duplicate_post_admin_script.js

This PR:
* ports the feature "Show original" from `svntrunk` branch + derivatives, adding PHPDocs and passing WPCS tests.
* moves the styles for the Options page to a CSS file which is enqueued

Porting "Show original" from svntrunk + some a11y fixes

---

duplicate-post-admin.php
duplicate-post-common.php
duplicate-post.css

In this PR:
* improved accessibility of the checkbox "Delete reference to original item" in the Quick Edit and in the Metabox
* added the styles to the CSS file to improve the display of the checkbox in the Quick Edit
* added an action to enqueue the CSS file in the post list (for allowed users and allowed post types)
* in the Posts / Pages overview pages, clone a post/page using e.g. the row action "Clone" link
* open the Quick Edit for the copy and look at the "Delete reference to original item" checkbox, label and description:
* they should be accessible
* they should be displayed in the same line and with correct alignment
Must be also check that `duplicate-post.css` is enqueued (and then requested to the server) only if all these conditions are true:
* the user can perform …

Enqueue CSS file for Quick Edit (#17)

---

LICENSE
README.md
duplicate-post-admin.php
duplicate-post-options.php
duplicate-post.php
readme.txt

This PR changes the name of the plugin from 'Duplicate Post' to 'Yoast Duplicate Post' in:
* the opening comment in the main file
* the update notice
* the settings page title (browser window title)
* the settings page header
* the readme.txt header

Plugin renaming in different locations

---

compat/duplicate-post-jetpack.php
duplicate-post-admin.php

This PR adds a deprecation warning for `duplicate_post_blacklist_filter` to be substituted by `duplicate_post_excludelist_filter`.
The new filter is used by the JetPack compatibility functions to make sure that the custom fields related to the Publicize extensions are filtered out.
The new filter was already documented in [the developer's guide](https://developer.yoast.com/duplicate-post/filters-actions#duplicate_post_excludelist_filter).
We can use the code in `compat/duplicate-post-jetpack.php` to test the change: it hooks a function to the filter that prevers from copying custom fields named `_wpas*`, `_publicize*`, `_jetpack*` (these are wildcards).
1. Edit a post
2. Add some custom fields: at least one which does not match the wildcards above and one which does.
3. Save the post
4. …

Deprecates duplicate_post_blacklist_filter in favor of duplicate_post_excludelist_filter

---

duplicate-post-options.php

The "More info on the template tag" link in the options page is outdated, and redirects to a non-existent page ([this link][old link] redirects [here][old link redirect]), so I've updated the link to head to the new documentation on developer.yoast.com
[old link]: https://duplicate-post.lopo.it/docs/developers-guide/functions-template-tags/duplicate_post_clone_post_link/
[old link redirect]: https://developer.yoast.com/duplicate-post/overviewfunctions-template-tags/duplicate_post_clone_post_link/

Update template tag documentation link

---

duplicate-post-admin.php

* The update notice is currently displayed on all admin screens until dismissed, and it's restored any time the plugin is upgraded from an earlier version. We should show the notice only on selected screens (Dashboard and Plugins list), and restore it (if dismissed) only when upgrading from a version before the first Yoast-branded one.
*  Change update notice behaviour to be shown only on selected screens, and to be restored only for users upgrading from version below 3.2.5
* The change is applied to `develop` branch, expecting it to be rolled out in a bugfix patch release.
1. Either install Duplicate Post version < 3.2.5 or change the value of `duplicate_post_version` in …

Improve update notice 

---

duplicate-post-admin.php

* WordPress 5.5 has introduced the default value `comment` for `comment_type` instead of the empty string (see [Trac issue](https://core.trac.wordpress.org/ticket/49236)). The comments having that value already set don't get copied even if the related option is enabled.
Moreover, that change is meant to pave the way for custom comment types, so it sounds more reasonable to explicitly filter out pingbacks and trackbacks.
*  Update check for comment type to make it compatible with values other from "pingback" and "trackback".
* The change is applied to `develop` branch, expecting it to be rolled out in a bugfix patch release.
1. Set up a new install of WordPress 5.5
2. Checkout the …

Update check for comment type after WordPress 5.5 changes

---

composer.json
duplicate-post-admin.php

This quick PR aims to fix a couple issues where a string value e.g. `1` is checked against `intval` thus unexpectedly evaluating to false. This happens when checking the options for the post attributes to copy set in the settings.
Also fixes minor coding standards.
To test:
- on the `future` branch
- go to Settings > Duplicate post > Post/page elements to copy
- make sure "Author" is checked
- go to the posts overview page
- clone a post that was authored by a user other than your user
- observe the cloned post now has your user as the author
- expected: the original author to be copied as author of the cloned post
Switch to this branch
- repeat the steps above
- see the author is now copied
Fixes [P3-246]

Fix intval checks

---

.travis.yml
composer.json
composer.lock
duplicate-post-admin.php
duplicate-post.php
readme.txt
src/class-duplicate-post-user-interface.php
src/class-duplicate-post.php

* We want to ensure that future expansion of the code remains stable and testable by switching over to a class-based folder structure use autoloading in Composer.
* Introduces class autoloading in Composer and initial class folder structure.
Please note this is a first pass at implementing autoloading. There are some architectural choices that should be discussed with architects (e.g. folder structure, Coding Standards to use) and there are no tests for now.
- adds a basic autoloading implementation
- adds initial class folder structure: note that at the moment the file names and class names are based on the WordPress PHPCS
- adds the class folder to the coding standards checks
- introduces a main class `Duplicate_Post`
- …

P3-251 Introduce autoloading and initial class folder structure

---

duplicate-post-common.php

* Code quality/Bug prevention
* Code quality/Bug prevention
Strict type comparisons should be used as a rule, with loose type comparisons being the exception.
This is especially important when comparing variables which are expected to be strings, as when one of the two operands - for whatever reason, other plugins interfering, errors etc - is not a string, the other operand will be juggled to the type of the first operand which can lead to unexpected results and hard to debug bugs.
For array functions which do loose type comparisons, setting the third `$strict` parameter to `false` can be seen as a clear indication that this is a conscious, well thought out decision by the developer.
In all other cases, `$strict` `true` should be …

QA: use strict type checking when using `in_array()`

---

duplicate-post-admin.php

* Code quality/performance/PHP cross-version compatibility
* Code quality/performance/PHP cross-version compatibility
In both cases, `esc_htm()` is already used, so there is no need for the additional call to `htmlspecialchars()`.
This fixes a PHP cross-version incompatibility as the default charset value for `htmlspecialchars()` has changed across PHP versions, which means that the output could previously be inconsistent across PHP versions.
* _N/A_ This change should have no effect on the functionality.

QA: remove two redundant htmlspecialchars() calls

---

duplicate-post-admin.php

* I18n
* I18n
All translators comments in a plugin should use the same comment style, commonly `/* ... */`, otherwise some PO generation tools will not pick up on them.
* _N/A_

QA: translators comments should use same style

---

compat/duplicate-post-gutenberg.php
compat/duplicate-post-wpml.php
duplicate-post-admin.php
duplicate-post-common.php
duplicate-post-options.php
duplicate-post.php

* Improved code documentation
* Improved code documentation
* Have only one file comment.
* Only use docblock syntax for documenting structural elements.
* Always have a blank line above a docblock.
* Use short form type keywords, i.e. `int` instead of `integer`, `bool` instead of `boolean`.
* Alignment of variable names and descriptions in `@param` and `@global` tags.
* Remove redundant variable name in `@return` tag. The variable name is an implementation detail and not exposed to the calling function.
* Remove stray punctuation. Proper punctuation should definitely be used when there is a description, but if a `@return` tag only provides the `type` without further description, there should not be a period `.` at the end.
Fix a …

Docs: various fixes

---

.travis.yml
composer.json
composer.lock

* Update dev dependency for compatibility with Composer 2.0
* Update dev dependency for compatibility with Composer 2.0
The DealerDirect PHPCS Composer plugin is the only dependency which needs an update for compatibility with Composer 2.0.
Version `0.7.0`, which was released last June, is compatible with both Composer 1.x as well as 2.x.
This also removes the need for the `composer self-update` in the Travis script.
Ref:
* https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/
* Using `master`:
- Using Composer 1.x, run `composer install` and see it works.
- Update to Composer 2.x `composer self-update --2`
- Run `composer install` again and see it …

Composer: update dependency for Composer 2.0 compatibility

---

.travis.yml

* Improve QA/CI
* Improve QA/CI
Lint files against PHP 8 as well and lint the new `src` directory too.
* Check the Travis output: has the additional build been added ? And does the linting of the files run correctly ?
Note: until PHP 8 is released, the build will be allowed to fail.

Travis: lint files against PHP 8 as well

---

src/class-duplicate-post-user-interface.php

* We want to allow post duplicated for Rewrite & Republish to share the same keyphrase with the original post without triggering the Previously Used Keyword analysis assessment, which would be misleading for these temporary copies.
* Allows previously used keyphrases on duplicated posts intended for Rewrite & Repubish.
- needs https://github.com/Yoast/wordpress-seo/pull/16319 which adds a filter to enable / disable the analysis assessment
- triggers the filter to disable the assessment based on a post meta set on the posts intended for Rewrite & Repubish
- this PR _does not_ add the post meta: there's another issue for that, see P3-230
- activate Yoast SEO, switch it to …

P3-235 allow duplicate focus keywords

---

duplicate-post.css
js/src/duplicate-post-edit-script.js

* We want to match the design of the copy links in the classic editor and block editor.
* Improves the styling of the copy links in the Classic editor and Block editor.
*
**Preliminary step:**
- run `grunt build:js` so that the new CSS classes are applied to the links in Gutenberg
**Test in the Classic Editor first:**
- install and activate the Classic Editor plugin
- edit a published post using the Classic Editor 
- observe the publish box in the right sidebar
- compare with [the design](https://www.sketch.com/s/2ec4254a-9529-4616-abe7-f6262c2ed6dd/a/j5b9r7) and make sure that:
- the 3 links "Copy to a new draft", "Rewrite & Republish", and "Move to trash", are equally …

P3-258 Style the copy links in the editors

---

src/ui/class-post-states.php
src/ui/class-user-interface.php
tests/ui/class-post-states-test.php

* We want users to be able to distinguish the Rewrite & Republish copies from the other posts and display the link to the original post
* Displays the Rewrite & Republish copies status and link to the original in the Posts list.
- After conversation with @enricobattocchi we decided to always display the bold text "Rewrite & Republish of {original post title}" regardless of user settings.
- go in the WordPress posts list
- make a clone of a post by clicking the link "Clone"
- make a new draft of the same post by clicking the link "New Draft"
- go back to the posts list
- make a Rewrite & Republish copy of the same post by clicking the "Rewrite & Republish" link
- go back …

P3-278 Display status and link to original for Rewrite & Republish copies.

---

Gruntfile.js
config/grunt/task-config/aliases.yaml
config/grunt/task-config/clean.js
config/grunt/task-config/copy.js
config/grunt/task-config/shell.js
config/webpack/webpack.config.js

* We need a `grunt artifact` task to automatize the generation of RC and releases.
* Introduces `grunt artifact` task to generate plugin zip files.
* For the moment the i18n part is completely left out. We'll see later if we need to do anything or just rely on WordPress.org translation project.
* checkout the branch
* build as usual.
* see that the build is successful (so the changes didn't break anything) and do a quick test to see the plugin is working (mainly check if the links in the block editor are there, and if they are working)
* run `grunt artifact` to generate a zip
* install the zip in a test, non dev WP site (e.g. Local by Flywheel) and check the plugin is …

P3-284 Introduce grunt artifact task

---

js/src/duplicate-post-edit-script.js
src/class-permissions-helper.php
src/class-post-republisher.php
tests/class-permissions-helper-test.php
tests/class-post-republisher-test.php

* We want to fix the post saving flow when a post copy for Rewrite & Republish is saved as draft, pending, private, future, etc.
* Addresses the cases when a Rewrite & Republish post copy is saved with a status other than `private` and the one for republishing.
- when users click the button to publish the post, we want to allow only posts with a status of `dp-rewrite-republish` or `private` to overwrite the original
- worth reminding in WordPress `private` posts can only be published
- all Rewrite & Republish post copies with other statuses should follow the normal WordPress flow e.g. be saved as draft, pending, future, etc.
In Gutenberg:
- in all the following cases, the …

P3-280 Handle the cases when a copy is saved as draft, pending, private, etc.

---

js/src/duplicate-post-edit-script.js
src/class-post-duplicator.php
src/class-post-republisher.php
src/ui/class-classic-editor.php
src/ui/class-user-interface.php
tests/ui/class-classic-editor-test.php

* We want to remove the ability for users to edit the slug for the Rewrite & Republish copies.
* Removes slug editing ability from the user interface for the Rewrite & Republish copies.
- when creating a copy, the post slug (`post_name`) is not NOT copied to the copy
- additionally, the UI to edit the post slug is removed from both classic and block editor
Build with `composer install && yarn && grunt build:js`
**Gutenberg:**
- edit a Rewrite & Republish copy
- check in the Post sidebar there's no "Permalink" panel
- edit a normal post
- check in the Post sidebar the "Permalink" panel is there
**Classic Editor:**
- activate the Classic Editor plugin
- edit a Rewrite & …

P3-281 Remove slug editing from Rewrite & Republish copies

---

src/class-duplicate-post.php
src/class-post-republisher.php
src/class-revisions-migrator.php
tests/class-post-republisher-test.php
tests/class-revisions-migrator-test.php

* When a post has been overwritten with the content of a Rewrite & Republish copy, we also want to merge the two revisions history so that the revisions of the copy (which will eventually be deleted) is not lost.
* Merges the revision history of a Rewrite & Republish copy into the one of its original.
* As it has happened in previous PRs, we also moved some calls to `register_hooks()` method outside the constructors for easier testing.
* Most of the main method from the new `Revisions_Migrator` class come from the `wp_save_post_revision()` function from `wp-includes/revision.php`
* The creation of a new revision on overwriting has been disabled by removing a default WP hooked function.
This PR can be acceptance tested by …

P3-288 migrate revisions

---

js/src/duplicate-post-edit-script.js
src/ui/class-block-editor.php
tests/ui/class-block-editor-test.php

* When a post is published in the block editor, the status update does not trigger a page reload. The R&R link is then hidden until you hit F5, or exit the edit screen and open it again. We should fix this
* Shows the Rewrite & Republish link in the Block editor immediately after the post has been published.
* The link wasn't display on publish because it wasn't created in the first place on the server side. We changed the link creation so it's created and passed to JS, but displayed only when the current post status is `publish`
* make sure you have the Rewrite & Republish link enabled in the settings (third tab)
* create a new post with block editor, do not publish it
* …

P3-263 update R&R link in block editor

---

js/src/duplicate-post-edit-script.js
js/src/duplicate-post-functions.js
js/src/duplicate-post-strings.js
src/ui/class-classic-editor.php
src/ui/class-post-submitbox.php

In P3-273, the changes overview page was created. In order for this to work, the post (draft) has to be saved first, before clicking the "Do you want to compare your changes ..." link . If the post is not saved, a “Leave site?” pop-up appears. As this might be confusing for users, since they need to cancel the pop-up, then cancel the pre-publish screen, then save the draft and then eventually go back to click the link again. [See this loom for clarification of the problem.](https://www.loom.com/share/5fb1697e52854ab79cfa9994e7b1b252)
So product decided for the link to become normal text and to add a "Save and compare" button under it, which saves the post and sends you to the changes overview screen. 
[Design block editor.](https://www.sketch.com/s/2ec4254a-9529-4616-abe7-f6262c2ed6dd/a/O7 …

Change link in block editor

---

js/src/duplicate-post-edit-script.js
src/ui/class-block-editor.php
tests/ui/class-block-editor-test.php

* The block editor class doesn't have a check for the "Edit screen" setting.
* Includes the edit screen option in the block editor.
*
* Make sure all `Show these links` options are enabled (i.e., `New Draft`, `Clone`, `Rewrite & Republish`).
* Go to Settings > Duplicate Post > Display and from `Show links in` disable the `Edit Screen` option. Save your changes.
* In the block editor, edit a published post without a Rewrite & Republish copy.
* See that there is no `Copy to a new draft` or `Rewrite & Republish` link in the sidebar (above the `Move to trash` button).
* Go to Settings > Duplicate Post > Display and from `Show links in` enable the `Edit Screen` option. Save …

P3-295 Include edit screen option for block editor

---

js/src/duplicate-post-strings.js
src/ui/class-asset-manager.php
src/ui/class-classic-editor.php
tests/ui/class-asset-manager-test.php
tests/ui/class-classic-editor-test.php

* Currently on Classic editor the label for choosing the date is "Publish on:", For Rewrite & Republish copies it should become "Republish on:" as it happens on Block editor
* Fixes the label for the date choser in Classic editor for Rewrite & Republish copies.
* Also fixes a dependency error, and changes the dependency list for the Block Editor script
* Activate Classic editor, disable Yoast SEO if you have it (and any other plugin if possible)
* edit a Rewrite & Republish copy
* see that the label for the date shows "Republish on:" (this comes from PHP)
* change the date to a future one so that the label changes to "Schedule for:"
* change the date back to a past date …

P3-298 Fix "Publish on" strings

---

src/ui/class-bulk-actions.php

* Removes the Republish & Rewrite action from bulk actions, when the user is viewing trashed posts, as it makes no sense to have that option there.
* Removes the Republish & Rewrite action from bulk actions, when the user is viewing trashed posts.
*
* Checkout this branch, run `composer install`, `yarn` and `grunt build`.
* Go to the posts overview.
* In the posts overview, see that the Rewrite & Republish action is available in the bulk actions list.
* Trash one or more posts.
* Go to the trashed posts, see that the Rewrite & Republish action is no longer available in the bulk actions list.
* Go to the posts overview.
* In …

Ensure Rewrite & Republish bulk action isn't available for trashed posts

---

src/ui/class-block-editor.php
tests/ui/class-block-editor-test.php

* We want the SEO analysis results to not give potentially confusing feedback for the Rewrite and Republish original and duplicate posts.
* Disables the duplicate focus keyphrase SEO analysis assessment for the Rewrite & Republish original posts.
* In https://github.com/Yoast/duplicate-post/pull/56 we disabled the duplicate focus keyphrase assessment for the R&R duplicate posts, following what was specified in https://yoast.atlassian.net/browse/P3-235
* This PR uses the same approach to disable the assessment also for the R&R original posts, i.e. the ones that are published and have a copy meant for R&R .
- Activate Yoast SEO and Yoast Duplicate Post
- Edit a published …

P3-302 Disable duplicate focus keyphrase assessment on Rewrite and Republish original post

---

src/ui/class-bulk-actions.php

* Removes the Republish & Rewrite action from bulk actions, when the user is viewing _draft_ posts, as Republish & Rewrite is only meant for published posts.
* Fixes a bug where the Republish & Rewrite bulk action was displayed in the Drafts posts list.
*
- Checkout this branch, run composer install, yarn and grunt build.
- Go to the posts overview.
- Make sure you have at least one draft post and one trashed post.
- In the posts overview, see that the Rewrite & Republish action is available in the bulk actions list in the following posts lists (the links at the top of the list):
- All
- Mine (available only if you're author of at least one post)
- Published
- Go to the …

Ensure R&R doesn't show up in the bulk actions in the drafts posts list.

---

src/class-permissions-helper.php
src/ui/class-block-editor.php
src/ui/class-bulk-actions.php
src/ui/class-post-list.php
src/ui/class-user-interface.php
tests/class-permissions-helper-test.php
tests/ui/class-block-editor-test.php
tests/ui/class-bulk-actions-test.php

* Rewrite & Republish has some issueS when working with Elementor. We decided to disable the new feature when Elementor is active while we work to make it compatible.
We need to:
1. prevent the creation of new Rewrite & Republish copies by disabling all the occurrences of the R&R command
2. hide existing R&R copies so users can't edit and republish them
* Disables the Rewrite & Republish feature when Elementor is active.
* We adapted the existing tests but didn't add new ones for time constraints.
* Install Elementor, do not activate it yet
* create a number of R&R copies from existing posts, do not republish them
* see that you can see them in the post list
* Activate …

P3-310 disable Rewrite & Republish when Elementor is active

---

src/ui/class-post-list.php

* 
* Fixes a bug which affected some installations (e.g. with WooCommerce)
*
* Be sure that you have WooCommerce disabled
* build and activate Yoast Duplicate Post from `release/4.0`
* see that everything's working fine
* activate WooCommerce
* see that you get a `Fatal error: Uncaught Error: Call to undefined function get_current_screen()`
* switch to this branch and build
* reload the page with the Fatal error and see it's gone now
* enable Elementor and see that the change did not affect the hiding of the R&R copies #89 + the recount of the posts #90
* [] QA should use the same steps as above.
* Activate alongside …

Fix fatal errors when `get_current_screen` is not available

---

duplicate-post-admin.php

* We have to upgrade the plugin notice for version 4.0
* Updates the upgrade notice for version 4.0
* We have removed some outdated code which was needed to ensure compatibility with WP < 4.7
* visit the WP Dashboard or the Plugins page
* If you already tested a 4.0-RCx version and dismissed the notice, you'll have to visit Settings→Duplicate Post, third tab "Display", tick the "Show upgrade notice" checkbox and save.
* Observe that the notice matches the design:
* click on the link to see you arrive to the page about Duplicate Post on the yoast.com website.
*
This PR affects the following parts of the plugin, which may …

Update upgrade notice for version 4.0

---

src/admin/class-options-form-generator.php
src/class-permissions-helper.php
src/class-utils.php
tests/admin/class-options-form-generator-test.php

* WooCommerce already has its own duplication feature which can't be disabled and is more suitable (supporting variable products etc). Letting users enable the plugin for WC Products can be misleading and confusing (with multiple links to create copies).
* Disables the plugin for WooCommerce products, introduces filter for enabled post types.
* The PR adds a filter calles `duplicate_post_enabled_post_types` to allow users to enable/disable post types overriding the options.
* make sure you have WooCommerce active with at least one Product.
* visit Settings->Duplicate Post, second tab "Permissions", and see that the checkbox for Products is missing.
* visit the list of …

P3-299 Disable for WooCommerce products

---

config/grunt/task-config/copy.js
duplicate-post-admin.php
src/class-permissions-helper.php
src/class-post-republisher.php
src/handlers/class-bulk-handler.php
src/ui/class-classic-editor.php
src/ui/class-post-list.php
src/ui/class-post-states.php
src/ui/class-row-actions.php

* We should avoid typehinting in functions which are hooked (directly or indirectly) to WP filters, because they can lead to fatal errors
* Fixes a bug that caused a fatal error when used with some plugins
* Fixed also a bug that prevented the upgrade notice to be displayed to users upgrading from versions 3.2.5 and 3.2.6
* Added a check to avoid a notice when current_screen is not set yet
* Cherry-picked from `develop` a fix in the creation of artifact (missing logo in upgrade notice)
* install and activate the `Members` plugin
* visit "Members"->"Roles" and edit a role
* see that you don't get a fatal error
* install and activate the `Classic editor` plugin
* edit a …

Patch typehinting fatal error

---

src/ui/class-admin-bar.php
src/ui/class-block-editor.php
src/ui/class-classic-editor.php
src/ui/class-column.php
src/ui/class-link-builder.php
src/ui/class-metabox.php
src/ui/class-post-list.php
src/ui/class-post-states.php
src/ui/class-row-actions.php
src/watchers/class-bulk-actions-watcher.php
src/watchers/class-copied-post-watcher.php
src/watchers/class-link-actions-watcher.php
src/watchers/class-original-post-watcher.php
src/watchers/class-republished-post-watcher.php

* We should enforce stricter checks and add missing ones to avoid fatal errors and warnings when parameters from hooks don't match the expected types.
* Fixes a bug where errors or notices could be triggered when using the plugin with some other plugins or custom code.
*
* checkout and build branch `master`
* edit class-post-list.php at line 82 to add a line like:
```
$post_type = [];
```
or
```
$post_type = new stdClass();
```
or
```
$post_type = false;
```
or whatever is not a string or an integer
* visit the post list (with WP_DEBUG defined) to see warning and notices about that
* checkout and build PR branch
* edit class-post-list.php at line 104 to add a line like: …

Enforce missing checks

---

readme.txt

* Corrects the spelling for "untranslated" and "translating"
* Uses existing phrase for [stronger link text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#strong_link_text) than "here"

Fix typos and improve link text

---

src/class-post-duplicator.php
src/class-post-republisher.php
src/class-utils.php

* Visiting `duplicatePost.originalEditURL` triggers the deletion of the R&R copy even if it's not been rewritten yet. We should avoid that.
* Prevents accidentale deletion of a R&R copy via redirect if it's not been republished yet
*
* create a R&R copy and edit it on block editor
* using the console, copy the value for `duplicatePost.originalEditURL` and paste it as address for a new browser tab, then visit it
* see that you get a `wp_die` "An error occurred while deleting the Rewrite & Republish copy."
* visit the post list, or reload the tab where you were editing the copy, to see the copy is still there
* republish the copy via Republish button to see everything's …

Prevent accidental deletion of copy when it's not been republished yet

---

duplicate-post-admin.php
src/class-post-duplicator.php

* R&R-related meta fields are copied when creating a regular copy. We should avoid that.
* Fixes a bug where Rewrite & Republish notices would be shown for regular copies.
* We filter out not just the `_dp_has_rewrite_republish_copy` which is the one triggering the notice, but also every other Duplicate  Post-related fields (see last commit from #96)
* create a R&R copy of a published post. 
* go back to the post list, and create a regular copy from the same original
* edit this second copy
* see that you see a `A duplicate of this post was made. Please note that any changes you make to this post will be replaced when the duplicated version is republished.` notice which …

P3-336 Prevent copying of R&R related meta fields when creating regular copies

---

src/ui/class-block-editor.php
tests/ui/class-block-editor-test.php

* #100 prevented status changes in Elementor for R&R copies by removing the control. This triggers some problems because Yoast SEO can't detect the post_status and so editing the Yoast SEO data triggers an unexpected warning (intended for published posts, while R&R are drafts). We should hide the control using CSS instead of removing it.
* Hides the post status changer in Elementor for Rewrite & Republish copies instead of removing it
*
* install and activate Yoast SEO and Elementor
* build Duplicate Post from the PR branch and activate
* create a R&R copy from a published post and edit it with Elementor
* open the Elementor settings (with the cog icon in the bottom left …

P3-337 Hide the post status changer in Elementor instead of removing it

---

js/src/duplicate-post-elementor.js
src/ui/class-block-editor.php
tests/ui/class-block-editor-test.php

* Saving changes of regular copies in Elementor triggers the redirect that should be reserved to R&R copies, so Duplicate Post tries to delete the post but it's prevente to do so and displays a `wp_die` message
* Fixes a bug where editing posts with Elementor could trigger a fatal error.
*
* Install and activate Elementor
* Install and activate Duplicate Post 4.1
* Create a regular copy of a post/page, and edit it with Elementor
* make some changes, then hit "Publish" or "Update" (depending if it's already published)
* see that you are redirected and you see "An error occurred while deleting the Rewrite & Republish copy."
* Switch to this branch and build
* Create a …

P3 344 prevent wp die error editing copies

---

composer.json

* We want to use an authoritative classmap to make sure the autoloader doesn't waste time looking for not found classes elsewhere.
* Changes the composer configuration to use authoritative classmap
*
* build the plugin and see you get no errors on `composer install`
* navigate the WP backend with Duplicate Post active and see you don't get any errors/warnings, and everything works fine
* run `grunt artifact` to create a zip
* install the zip on another WP install (e.g. Local by Flywheel) and see you don't get any errors/warnings, and everything works fine
* QA doesn't need to test this PR
This PR affects the following parts of …

P3-343 Make classmap authoritative

---

duplicate-post-admin.php

* In 4.0 we introduced a new format for the "Display links in" option.
Unfortunately the upgrade routine runs at every upgrade, so if you upgrade from a 4.0.* version the old options have been deleted and the default value (links visible everywhere) is then used.
* Fixes a bug where the "Show links in" settings were reset to the default value on version upgrade.
*
* Install Duplicate Post 4.0.2 (or 4.1.1 if you are testing this in 4.2-RC1)
* visit the Settings, third tab "Display", and make sure you disable the displaying of the plugin in some locations: e.g. Admin bar, then Save
* upgrade to this branch
* visit the Settings, third tab "Display", and check that the …

P3-350 Fix options reset bug on upgrade

---

duplicate-post-common.php

* The filter introduced in #92 should be used in legacy code as well.
* Fixes a bug where a post type enabled by filter couldn't be copied.
*
* Install and activate WooCommerce
* edit your theme's functions.php and add these lines at the end of the file, then save:
```
function test_add_product( $post_list ) {
$post_list[] = 'product';
return $post_list;
}
add_filter('duplicate_post_enabled_post_types', 'test_add_product');
```
* visit the product list, make sure there is some Product items (if not, create one)
* use the "Clone" or "New Draft" link, or the "Clone" bulk action, to create a copy of a product
* See that you don't get a `wp_die` with the error "Copy features …

P3-359 Add missing filter for post types in legacy code

---

src/handlers/class-check-changes-handler.php
tests/bootstrap.php
tests/handlers/class-check-changes-handler-test.php

* ACF fields are displayed in the standard WP revisions comparison screen. Since we are mimicking that to compare the R&R copy to its original, we should make sure it happens there as well.
* Allows plugins such as ACF to add fields to the "Compare changes" screen for Rewrite & Republish
* The comparison screen ID is set to `revision` to make sure that some checks from ACF pass
* Added the `OBJECT`, `ARRAY_A` and `ARRAY_N` defines to the tests bootstrap
* Install and activate ACF. If possible, use ACF PRO (ping me if you need it)
* Define some custom fields, or import this set of fields
[acf-export-for-PRO.json.zip](https://github.com/Yoast/duplicate-post/files/5972845/acf …

P3-342 Show ACF fields in comparison

---

src/handlers/class-check-changes-handler.php

* WP 5.7 has introduced some changes int its "compare revisions" screen and relative functions. This breaks how we use those functions to mimick its look for the Rewrite & Republish "Compare changes" screen.
* #106 introduce a notice in the comparison screen, this also fixes that (see "Relevant technical choices")
* Fixes a bug where the "Compare changes" screen for the Rewrite & Republish feature displayed a broken layout in WordPress 5.7.
* #106 set the `current_screen` object to `revision` to make sure that changes introduced there would be working. This triggered a warning notice:
```
NOTICE: wp-includes/admin-bar.php:708 - Trying to get property 'post_type' of non-object …
```

P3-434 Fix R&R comparison screen in WP 5.7

---

src/ui/class-metabox.php
tests/ui/class-metabox-test.php

* The current implementation of the Metabox class has been copied directly from the legacy code. It uses WP function and hooks in a wrong way and forces to use JS to hide the custom metabox for post that are not copies.
* Refactors the Metabox class.
*
* visit `Settings` > `Duplicate Post`, third tab `Display`, and make sure the `Show original item:` > `In a metabox in the Edit screen` option is enabled.
* Make sure you have at least:
* 1 post which is not a copy of anything
* 1 post which is a R&R copy of another post
* 2 posts which are regular copy of other posts
* 1 page which is a regular copy of another page
* **perform the following steps both in Block and Classic …

P3-321 improve Metabox class

---

compat/duplicate-post-wpml.php
duplicate-post-admin.php
duplicate-post-common.php
duplicate-post.php
src/handlers/class-check-changes-handler.php
src/ui/class-bulk-actions.php

YoastCS enforces the use of short arrays.
This plugin was using a mixture of both long as well as short arrays. This has now been fixed up to always use short arrays.
* _N/A_

CS: use short arrays

---

tests/class-utils-test.php
tests/ui/class-asset-manager-test.php
tests/ui/class-link-builder-test.php

* Code quality
* Code quality
Import `use` statements ALWAYS have to refer to the fully qualified name of a class/function/constant, so using a leading backslash is not necessary and strongly discouraged.
* _N/A_

QA: no leading backslash for import use statements

---

src/admin/class-options.php
src/ui/class-block-editor.php
tests/admin/class-options-form-generator-test.php
tests/class-post-duplicator-test.php
tests/class-testcase.php
tests/ui/class-block-editor-test.php
tests/ui/class-classic-editor-test.php
tests/ui/class-link-builder-test.php
tests/ui/class-row-actions-test.php

* Code quality
* Code quality
Closures not using `$this` should be declared as `static`.
Includes minor whitespace fixes for the space between the `function` keyword and the opening parenthesis.
* _N/A_

QA: declare static closures as static

---

duplicate-post-admin.php
duplicate-post.php

* Code modernization
* Code modernization
Now support for PHP < 5.6 has been dropped, the `__DIR__` constant can be safely used.
* _N/A_

Modernize: use __DIR__ instead of dirname( __FILE__ )

---

compat/duplicate-post-gutenberg.php
duplicate-post-admin.php
duplicate-post-common.php
src/class-post-duplicator.php
src/handlers/class-check-changes-handler.php
src/handlers/class-link-handler.php
src/ui/class-column.php
src/ui/class-link-builder.php

YoastCS prohibits the use of Yoda conditions as it decreases the readability of code.
There are other sniffs in place to prevent accidentally using an assignment in a condition (which is what Yoda conditions is supposed to prevent).
* _N/A_

CS: don't use Yoda conditions

---

src/admin/class-options-page.php
src/class-revisions-migrator.php
tests/admin/class-options-page-test.php
tests/class-revisions-migrator-test.php
tests/handlers/class-check-changes-handler-test.php
tests/ui/class-block-editor-test.php
tests/ui/class-row-actions-test.php
tests/watchers/class-bulk-actions-watcher-test.php
tests/watchers/class-copied-post-watcher-test.php
tests/watchers/class-original-post-watcher-test.php

Variety of whitespace fixes:
* One blank line at the start of a class.
* One blank line between function declarations.
* No blank line at the end of a class.
* No space between an incrementor/decrementor and the variable it applies to.
* Multi-line chained object method calls should be indented one tab from the line containing the start of the statement.
* _N/A_

CS: various whitespace fixes

---

src/class-utils.php
src/handlers/class-bulk-handler.php

* When using increment/decrement operators, pre-in/decrement should be favoured over post-in/decrement.
Note: there is a difference in behaviour: the "pre" variant increments and returns, the "post" variant returns and increments after. This is a significant difference and the reason why "pre" should be favoured, though for stand-alone statement there is - in effect - no difference.
* Also: there should be no whitespace between the increment/decrement operator and the variable it applies to.
* _N/A_

CS: use pre-increment/decrement

---

duplicate-post.php
src/class-revisions-migrator.php

* Code quality
* Code quality
Always use parentheses around arithmetic operations to prevent potential issues with operator precedence.
* _N/A_

CS: use parentheses around arithmetic operations

---

duplicate-post-admin.php
duplicate-post-common.php
duplicate-post.php
src/admin/class-options-form-generator.php
src/admin/class-options-inputs.php
src/admin/class-options-page.php
src/admin/class-options.php
src/admin/views/options.php
src/class-post-duplicator.php
src/class-post-republisher.php
src/class-utils.php
src/handlers/class-check-changes-handler.php
src/ui/class-classic-editor.php
src/ui/class-link-builder.php
src/ui/class-metabox.php
src/ui/class-row-actions.php
src/watchers/class-bulk-actions-watcher.php
src/watchers/class-link-actions-watcher.php
tests/admin/class-options-form-generator-test.php
tests/watchers/class-copied-post-watcher-test.php
tests/watchers/class-original-post-watcher-test.php

Variety of formatting fixes to docblocks.
* Blank line before a docblock.
* No blank line at the start of a docblock.
* Alignment of the parameter descriptions.
* Use a capital as the first character of a comment.
* Docblock tag order - the `@param` and `@return` and optionally `@throws` tags should always come last.
* Fix the indentation of a docblock.
* Fix the indentation of numerous translators comments.
Includes fixing up the file docblock of the main plugin file.
* _N/A_
This is a code-only change and should have no effect on the functionality. If the build passes (linting, test …

Docs: various minor formatting fixes

---

src/admin/class-options-form-generator.php

The `@ignore` tag is rarely used and only really supported by phpDocumentor. Unless phpDocumentor is used (which it is not for this project at this time), the tag should not be used.
* _N/A_

Docs: remove unsupported `@ignore` tag

---

tests/ui/class-classic-editor-test.php

* Code quality
* Code quality
Implicit array creation is a code smell.
* _N/A_

QA: fix implicit array creation

---

.phpcs.xml.dist
compat/duplicate-post-gutenberg.php
duplicate-post-admin.php
duplicate-post-common.php
src/class-post-duplicator.php
src/class-post-republisher.php
src/class-utils.php
src/handlers/class-link-handler.php
src/ui/class-admin-bar.php
src/ui/class-link-builder.php

YoastCS enforces that a potential `else[if]` starts on a new line, rather than straight after the closing `}` of the preceding `[else]if`.
* _N/A_

CS: else(if) must be on new line

---

duplicate-post-admin.php
src/handlers/class-check-changes-handler.php
src/handlers/class-link-handler.php
src/ui/class-row-actions.php
src/watchers/class-bulk-actions-watcher.php
src/watchers/class-copied-post-watcher.php
src/watchers/class-link-actions-watcher.php
src/watchers/class-original-post-watcher.php
src/watchers/class-republished-post-watcher.php

Boolean operator should be placed at the start of the line in multi-line conditions
This generally makes for a smaller diff if something changes and improves readability.
Same thing, but then for multi-line concatenation.
* _N/A_

 CS: consistent placement of operators

---

duplicate-post-options.php
src/admin/class-options-form-generator.php
src/admin/class-options.php
src/class-post-republisher.php
src/handlers/class-check-changes-handler.php
src/handlers/class-link-handler.php
src/ui/class-bulk-actions.php
src/watchers/class-link-actions-watcher.php
tests/admin/class-options-page-test.php
tests/admin/class-options-test.php
tests/class-post-republisher-test.php

* Code quality
* Code quality
When PHP encounters an unqualified function call in a namespaced file, it will first try and find the function within the namespace and only when it can not find it in the namespace, fall-back to the global function.
Using fully qualified function names when calling a global function ensures that PHP will bypass the search within the namespace and call the global function directly.
It also ensures that optimal use is made of the PHP7 opcodes on VM level which have been implemented for a select group of PHP internal functions resulting in faster code execution.
Ref: https://www.php.net/manual/en/language.namespaces.fallback.php
This PR can be tested by …

QA: call global functions using a fully qualified name

---

src/admin/class-options-page.php
src/class-post-republisher.php
src/handlers/class-check-changes-handler.php
src/handlers/class-save-post-handler.php
src/ui/class-asset-manager.php
tests/ui/class-asset-manager-test.php

* Code quality
* Code quality
When PHP encounters an unqualified constant in a namespaced file, it will first try and find the constant within the namespace and only when it can not find it in the namespace, fall-back to the global constant.
Using fully qualified constant names when using a global constant ensures that PHP will bypass the search within the namespace and use the global constant directly.
Ref: https://www.php.net/manual/en/language.namespaces.fallback.php
* _N/A_

QA: use global constants with a fully qualified name

---

composer.json

* Project documentation
* Project documentation
Set minimum supported PHP version in `require` and various other minor tweaks to the Composer file.
While this change does not have a serious effect while the package is not listed on (WP)Packagist, it still improves the documentation of the package.
* Run `composer show --self`.

Composer: set minimum supported PHP version in `require`

---

.travis.yml

* Improve CI setup
* Improve CI setup
* Be explicit about the expected OS.
* Cache composer downloads for faster builds.
* Use the `jobs` key. The `matrix` key has been deprecated quite a while back.
* Use `fast_finish`.
This will mark a build as "passed" as soon as all builds which are not allowed to fail have passed.
* Disable Xdebug when it's not needed.
Xdebug is only needed for code coverage builds and slows down the Composer `install` and test runs significantly, so conditionally disabling it.
* Use `travis_retry` for the `composer install` to prevent failed builds due to time-outs and rate limits.
* Validate the `composer.json` file just to be sure.
* Verify the …

Travis: various minor tweaks

---

.travis.yml
composer.json

* Improve CI setup
* Improve CI setup
As discussed.
The VIPCS rulesets have a couple of drawbacks:
1. As it stands, they can not be combined with WordPressCS as they will silence various sniffs from WPCS which we _do_ want to receive notice from.
2. The sniffs themselves are not always that accurate.
3. The sniffs will, at times, recommend using functionality only available on the VIP platform, which means that certain "issues" are not fixable.
It is the intention to include select sniffs - not the rulesets - from VIPCS is a future version of YoastCS.
With that in mind, the sniffing against VIPCS is being removed, in favour of inheriting sniffing against select VIP sniffs via YoastCS in the future.
This PR can be acceptance …

Composer/Travis: remove sniffing against VIPCS

---

duplicate-post-admin.php
duplicate-post.php

CS: remove a few more redundant @ignore comments

---

duplicate-post-admin.php
tests/bootstrap.php

* Code quality
* Code quality
Using fully qualified function calls in non-namespaced files is redundant and may actually cause PHP to throw a warning in certain circumstances.
* _N/A_

QA: no FQN function calls in non-namespaced file

---

duplicate-post-admin.php

* Security hardening
* Security hardening
The `duplicate_post_newsletter_signup_form()` is documented as returning an output escaped form, but didn't properly escape all variables.
* _N/A_ This should have no effect on functionality (other than when translators would have added HTML to the translated texts, which would now be correctly escaped).

QA: improve output escaping [1]

---

duplicate-post-common.php

* Security hardening
* Security hardening
As things were, if `$link` was passed in as a parameter, it would not be escaped for output. Output escaping was only applied to the default anchor text string.
Fixed now.
* _N/A_ This should have no effect on functionality (other than when translators would have added HTML to the translated texts, which would now be correctly escaped).

QA: improve output escaping [2]

---

src/admin/class-options-form-generator.php

These arrays are all input arrays for calls to the `generate_options_input()` method.
The `generate_options_input()` method already does the output escaping for the checkbox label on line 84, so these `esc_html()` calls can be removed.
* _N/A_

QA: remove double output escaping

---

duplicate-post-admin.php
duplicate-post.php

The `DUPLICATE_POST_PATH` constant is declared early in the plugin bootstrap file.
For consistency, it is recommended to use this constant throughout the application for file includes.
Note: the `DUPLICATE_POST_PATH` constant is based on `plugin_dir_path()` which returns the path with a trailing slash, so leading slashes in the "file name" part of the paths have been removed.
* Open any admin page on which this plugin is loaded. If there are no fatal errors, we're good ;-)

CS: consistency for file includes

---

src/class-utils.php

* Security hardening
* Security hardening
The return value of the `Utils::get_edit_or_view_link()` method is treated as properly escaped HTML ready for output, however, the escaping was incomplete.
Note: The `$title` variable should probably also be escaped, using `esc_html()`, however, I'm not 100% sure if the title can contain HTML.
If that's the case, it should probably be escaped with `wp_kses_post()`.
Second opinion needed.
* Check out this branch
* Open an admin page which uses this functionality
* Verify whether the link(s) still work correctly.

QA: improve output escaping [3]

---

.phpcs.xml.dist
admin-functions.php
compat/wpml-functions.php
composer.json
duplicate-post.php
src/admin/options-page.php
src/handlers/check-changes-handler.php
src/handlers/link-handler.php
src/handlers/save-post-handler.php
src/post-republisher.php
src/ui/bulk-actions.php
src/ui/classic-editor.php
src/watchers/bulk-actions-watcher.php
src/watchers/link-actions-watcher.php
src/watchers/republished-post-watcher.php
tests/bootstrap.php
tests/post-republisher-test.php
tests/ui/admin-bar-test.php
tests/ui/classic-editor-test.php
tests/watchers/republished-post-watcher-test.php

* Code consistency and code quality
* Code consistency and code quality
💡  **Pro-tip**: this PR will be easiest to review by going through each commit individually!
Also note: after this PR has been merged, **_all devs working on this plugin should run `composer update` to update their local dev environment._**
* Remove explicit `require`s for dependencies which are underlying dependencies of YoastCS.
This will allow YoastCS to manage the version constraints as of now and minimizes the risk of version conflicts.
* Require YoastCS.
* Remove exclude patterns which are inherited automatically from YoastCS.
* Replace use of the `WordPress` and `PHPCompatibilityWP` rulesets with the `Yoast` ruleset which includes both.
* Add some …

PHPCS: Switch over to using YoastCS

---

.travis.yml

* Improve CI
* Improve CI
As it was, the unit tests were only being run against PHP 7.4, while the plugin is supposed to be compatible with PHP 5.6 - 8.0.
To safeguard that properly, the tests should be run against all the supported PHP versions.
At this time, however, it is not (yet) possible to run the tests against PHP 8 due to the PHPUnit version being used (PHPUnit 5-7) in combination with certain tests features.
This will be fixed in the near future in a separate PR.
So, for now, this commit makes the following changes to the CI setup:
* Run the tests against all currently supported PHP versions, with the exception of PHP 8.0 which will be enabled at a later point in time.
* Only lint the code against high/low PHP versions, …

Travis: only lint against high/low PHP and run tests on more PHP versions

---

tests/handlers/check-changes-handler-test.php
tests/post-republisher-test.php
tests/ui/admin-bar-test.php
tests/ui/classic-editor-test.php
tests/watchers/bulk-actions-watcher-test.php
tests/watchers/link-actions-watcher-test.php
tests/watchers/republished-post-watcher-test.php

When a (WP) global variable or a PHP superglobal variable key is set from within a test, it should be cleaned up at the end of the test to make sure the variable being set does not unduly influence other tests.
* _N/A_
This is a code-only change and should have no effect on the functionality. If the build passes (test runs), we're good.

QA: clean up global variables set in tests

---

tests/ui/classic-editor-test.php

For PHPUnit assertions which expect an `$expected` and a `$result` parameter, the parameter order is always `( $expected, $result, ...).
While it may not seem important to use the correct parameter order for assertions doing a straight comparison, in actual fact, it is.
The PHPUnit output when the assertions fail expects this order and the failure message will be reversed if the parameters are passed in reversed order which leads to confusion and makes it more difficult to debug a failing test.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertSame
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals …

 QA: Unit tests: use the correct parameter order

---

tests/admin/options-form-generator-test.php
tests/admin/options-inputs-test.php
tests/admin/options-test.php
tests/permissions-helper-test.php
tests/post-duplicator-test.php
tests/post-republisher-test.php
tests/ui/bulk-actions-test.php
tests/ui/classic-editor-test.php
tests/ui/column-test.php
tests/ui/link-builder-test.php
tests/utils-test.php
tests/watchers/bulk-actions-watcher-test.php
tests/watchers/link-actions-watcher-test.php
tests/watchers/republished-post-watcher-test.php

Using strict assertions should always be preferred over loose type assertions. This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available has been extended hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertSame
This PR can be tested …

QA: use strict PHPUnit assertions

---

tests/admin/options-form-generator-test.php
tests/testcase.php

This fixes three different issues with the mocking of the WP_Role objects.
**1. Incorrect implementation of `allows()`.**
As per the Mockery documentation about the `allows()` syntax, the use of `allows()` can take two forms:
1. Passing it an array with `method_name` => `return_value` entries.
2. Not passing it any arguments, but chaining `method_name` and `andReturn( 'return value' )` to it.
In the Duplicate Post `TestCase` class method [1] was being used, but implemented incorrectly.
The `return_value` should be an actual value, not a callback which will be called to get at the value.
In practice, that meant that the mocked `WP_Role` `hap_cap()`, `add_cap()` and `remove_cap()` methods …

Tests: fix broken setup of mocked WP_Role objects + fix an incorrect test

---

src/admin/options-inputs.php
tests/admin/options-form-generator-test.php
tests/admin/options-inputs-test.php

Doing things the WP way
Ref: https://developer.wordpress.org/reference/functions/checked/
* Check out `develop`.
* Open the options page of this plugin and make sure there are some checked and some unchecked checkboxes.
* Take note of which checkboxes are checked and which unchecked.
* Check out this branch.
* Reload the options page and verify the checkbox state is still the same.
* Change the state of some checkboxes & save.
* Verify that the checkboxes display correctly in their new state.

QA: use the `checked()` function

---

tests/handlers/check-changes-handler-test.php
tests/testcase.php

Stub the `esc_html_e()` function and adjust the expected output in one test.
* _N/A_

Tests: stub the `esc_html_e()` function

---

tests/ui/classic-editor-test.php

Most tests in the `Classic_Editor_Test` would set an output callback to `$this->setOutputCallback( static function () {} );`.
For tests which do not produce output, this is redundant, so removing these.
The remaining calls to `setOutputCallback()` were used to "silence" expected output.
Expected output should generally be tested, not silenced. With that in mind, the remaining calls to `setOutputCallback()` have been replaced with calls to `expectOutputRegex()` with a regex based on the output generated by the function under test.
* _N/A_
This is a code-only change and should have no effect on the functionality. If the build passes (linting, …

Classic_Editor_Test: improve testing of expected output

---

.gitignore
.travis.yml
composer.json
phpunit.xml.dist
tests/admin/options-form-generator-test.php
tests/admin/options-inputs-test.php
tests/admin/options-page-test.php
tests/admin/options-test.php
tests/bootstrap.php
tests/handlers/check-changes-handler-test.php
tests/permissions-helper-test.php
tests/post-duplicator-test.php
tests/post-republisher-test.php
tests/revisions-migrator-test.php
tests/testcase.php
tests/ui/admin-bar-test.php
tests/ui/asset-manager-test.php
tests/ui/block-editor-test.php
tests/ui/bulk-actions-test.php
tests/ui/classic-editor-test.php
tests/ui/column-test.php
tests/ui/link-builder-test.php
tests/ui/metabox-test.php
tests/ui/post-states-test.php
tests/ui/row-actions-test.php
tests/watchers/bulk-actions-watcher-test.php
tests/watchers/copied-post-watcher-test.php
tests/watchers/link-actions-watcher-test.php
tests/watchers/original-post-watcher-test.php
tests/watchers/republished-post-watcher-test.php

* Safeguard compatibility with PHP 8
* Safeguard compatibility with PHP 8
👉 **Pro-tip**: this PR will be easiest to review by going through each commit individually.
* Adds a dev dependency to the `yoast/wp-test-utils` package, which will also make the PHPUnit Polyfills available.
* As that package already requires and manages the installable versions for BrainMonkey and PHPUnit, remove these as explicit requirements from `require-dev` in favour of letting the WP Test Utils package manage the versions.
This new package adds the following features:
* Polyfills for various PHPUnit cross-version changes.
* Basic test cases for use by the plugins.
Refs:
* https://github.com/Yoast/wp-test-utils
* …

Tests: make the testsuite compatible with PHPUnit 9 and test against PHP 8

---

tests/admin/options-page-test.php

* Improve validity of the tests
* Improve validity of the tests
The `Options_Page_Test::generate_page()` method does not exist. The `Options_Page::generate_page()` method does.
* _N/A_ If the tests pass, we're good.

Fix bug in test

---

src/ui/asset-manager.php
src/ui/classic-editor.php
tests/ui/block-editor-test.php
tests/ui/link-builder-test.php

* Improved compatibility for PHP 8.0.
* Improved compatibility for PHP 8.0.
... to prevent using reserved keywords as a parameter names.
While this isn't forbidden, in PHP 8.0+ with named parameters, this can lead to very confusing code, so better to use another name.
* _N/A_ This PR does not contain functional changes. If the build passes, we're good.

CS/QA: rename function parameters

---

admin-functions.php
src/ui/newsletter.php
src/ui/user-interface.php

Replaced MailChimp form with MailBlue form and integration.
Added `ui/newsletter.php` class which handles all of the `mailblue` newsletter integration and logic. Implemented some styling refinement.
* Replaces Mailchimp with MailBlue newsletter integration.
1. Newsletter subscription request is going to live API Url. Reason: Inability to automatically check for environment. Behavior of form stays the same.
2. User is subscribed to [Yoast newsletter](https://mbyoastbv.activehosted.com/app/contacts?limit=100&listid=6&status=1) list.
1. Enable `Duplicate post` plugin notice [here](http://basic.wordpress.test/wp-admin/options-general.php?page=duplicatepost), if not enabled.
1. Go to …

PLAT 907 Duplicate Post: replace MailChimp integration with MailBlue

---

src/post-republisher.php
tests/post-republisher-test.php

* We want to avoid that posts with `dp-rewrite-republish` status are being displayed or even queried for in the front-end. Closes #211 
* Fixes a bug where Rewrite & Republish copies could be displayed and queried in the front end.
* Also fixing some CS warnings in related test.
* visit the frontend with Debug Bar and/or Query Monitor installed and configured
* check that the main query does not have `OR $prefix.post_status = 'dp-rewrite-republish'` in the `WHERE`
* check that the R&R feature still works:
* create a R&R copy from a published post, change something and republish it (check the logs that everything goes right)
* create a R&R copy from a published post, …

DUPP-32 Set `dp-rewrite-republish` as `'public' => false`

---

src/post-republisher.php
tests/post-republisher-test.php

* We want to fix a bug where HTML tags in a Custom HTML block are stripped away whem a R&R copy is republished.
* Fixes a bug where HTML tags in a Custom HTML block would be removed when republishing a scheduled Rewrite & Republish copy.
* Also removes an unnecessary `wp_slash` call around a `WP_Post` object (`wp_update_post()` will take care of that)
* Create a new post in the block editor
* add a `Custom HTML` block and insert some code with tags like `script` and `style`, e.g.:
```
<style>
.whatever {
font-size: 35px;
}
</style>
<script>
alert(1);
</script>
```
* Publish the post 
* visit it in the front end and check that you can see the tags in the source (if you use …

DUPP-33 Fix scheduled republish bug

---

js/src/duplicate-post-edit-script.js
src/ui/block-editor.php
tests/ui/block-editor-test.php

* We want to prevent a fatal error in the plugin's script for the Block Editor when it's executed where it's not supposed to.
A plugin or a theme may (wrongfully) set the global var `$post` in the Widgets screen. This, paired with the fact that the Widgets screen executes the `enqueue_block_editor_assets` even if there is no post to be edited, trigger the execution of out `duplicate-post-edit.js` script, which fails because there is no `core/editor` store or `PluginPostStatusInfo` component available.
With the FSE transition undergoing, this might happen even more frequently.
* Fixes a bug where a fatal error would be triggered in the Widgets page.
* 
* build from …

DUPP-176 Prevent rendering of the script when the store is not available

---

admin-functions.php
src/ui/newsletter.php

We want the upgrade notice in Duplicate Post to become a "welcome" notice for first time users.
Implementation approved by UX (Corey), see [slack](https://yoast.slack.com/archives/C02GZJ2UFJ6/p1639994567313800?thread_ts=1639738929.266600&cid=C02GZJ2UFJ6). 
* Converts the upgrade notice into a welcome notice for first-time users.
* 
* Use a fresh install of the Yoast Duplicate Post plugin, or delete the `duplicate_post_show_notice` option in the `_options` table 
* Activate Yoast Duplicate Post.
* You should see a notice that matches the screenshot (see summary above).
* Dismiss the notice.
* Make sure it does not reappear when refreshing the page.
* Deactivate and …

Dupp 177 welcome notice

---

.github/workflows/deploy.yml

* Improve CI
* Improve CI
By default the `actions/checkout` does a shallow clone. This means that other branches will not be known, so would always be created as new.
By setting `fetch-depth` to `0`, a complete clone will be made, including all tags and branches.
This will make the deploy slightly slower, but as the `dist` repos are nowhere near as huge as the `dev` repos, this should still be relatively limited.
If this at some point would become problematic, we can have a think about using a "sensible number" for `fetch-depth` (something like `1000` or so).
Refs:
* https://github.com/actions/checkout#usage
* https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
This PR can be acceptance tested by …

GH Actions: fix the deploy fail

---

admin-functions.php
src/admin/options.php
src/admin/views/options.php
src/ui/newsletter.php

* We want to fix the link in the welcome notice, and change copy references to update notice → welcome notice
* Fixes an unreleased bug where the link to the privacy policy was broken.
* We also fixed the labels in the settings to refer to the welcome notice and not to update notice anymore
* install on a clean environment
* see the welcome notice, click on the "Privacy policy" link
* you should arrive to the page with URL https://yoast.com/privacy-policy/
* visit Settings > Duplicate Post
* navigate to the third tab "Display"
* check that the last checkbox has labels referring to `Welcome notice` and not to `Update notice` anymore:
QA can test this PR by following these …

DUPP-217 Fix welcome notice

---

admin-functions.php

* We want to hide the welcome notice to upgrading users, even if they have not dismissed the upgrade notice yet.
* Fixes an unreleased bug where the welcome notice would be displayed to existing users who haven't dismissed the upgrade notice.
* I failed to change the commit message so it's not meaningful. Sorry.
* install Local By Flywheel
* create two websites: one for a `New User`, another for an `Existing User`
* checkout this branch and create a ZIP with `grunt artifact`.
* in the website for the `New User`, install the `artifact.zip` file you created
* activate the plugin
* check that you **can** see the Welcome notice in the Dashboard and in the Plugins page.
* in …

DUPP-218 Always hide welcome notice to upgrading users

---

.github/workflows/cs.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml

* Improve CI
* Improve CI
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
* https://github.com/actions/download-artifact/releases
* https://github.com/actions/upload-artifact/releases

GH Actions: version update for various predefined actions

---

src/ui/classic-editor.php

* We want to fix the margins here:
* Fixes a bug where a section in the Classic Editor's submitbox would be displayed with incorrect margins.
*
* create a R&R copy and edit it
* check that the margins are now correct
*
*
Fixes [DUPP-572]
[DUPP-572]: https://yoast.atlassian.net/browse/DUPP-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DUPP-572 Apply core class to get margins right

---

src/ui/classic-editor.php
tests/ui/classic-editor-test.php

* We want to improve how some labels are rewritten for the R&R feature using `gettext`, to avoid performance issues.
* Reduces the impact of the plugin on the performance of the site by avoding useless calls on the `gettext` filter.
*
We should check that the labels are still rewritten, and that the number to the affecting methods is much lower.
* install the Classic Editor plugin
* Choose a published post and create a R&R copy of that
* while editing the R&R copy in the Classic Editor, check that the button says "Republish" and the field where you set the date says "Republish on:" (the wrong margin is being fixed in #254)
* change the date to a future date and check that …

DUPP-52 improve gettext usage

---

src/admin/views/options.php

* Plugin security
* Minor security improvement
`esc_attr*()` should be used for values in HTML attributes.
* _N/A_ Functionally, there should be no noticeable difference

QA: fix incorrect escaping function

---

.github/workflows/cs.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml

* CI maintenance
* CI maintenance
GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
Caches used in GH Actions …

GH Actions: various tweaks

---

tests/admin/options-form-generator-test.php
tests/bootstrap.php
tests/testcase.php
tests/ui/admin-bar-test.php

* Make the test suite compatible with PHP 8.2
* Make the test suite compatible with PHP 8.2
Document why a non-existent property is being set on `WP_Term` and that this is intentional.
Includes adding a missing negative function call expectation.
* While on PHP 7.4, run `composer install` to update the test dependencies to a set which is compatible with PHP 8.2 (this repo does not have a committed `composer.lock` file, so this should work).
* On PHP 8.2, run the tests against `trunk` and see them fail.
* On PHP 8.2, run the tests against this branch and see them pass.

Tests: fix PHP 8.2 compatibility

---

config/grunt/task-config/update-changelog-to-latest.js
readme.txt

* change ## 4.4 to = 4.4 = for wordpress.org
* change ## 4.4 to = 4.4 = for wordpress.org
*
*
*
*
Fixes #

Do fix worpdress org format

---

package.json
readme.txt
yarn.lock

* Update plugin-grunt-tasks 2.3 => 2.4
* this will change the initial date format (to yyyy-mm-dd) used when creating a new RC,
* updated a dependancy from master to main
* updates the date format in readme.txt
* Updates the `grunt-plugin-tasks` dependency to 2.4 ( this will change the initial date format to yyyy-mm-dd when creating a new RC).
* Updates the date format in README.md.
* Updates a dependency from `master` to `main`.
*
* verify the readme.txt
*
*
Fixes #

update plugin-grunt-tasks to 2.4 and update date format in readme.txt

---

README.md

* Fix broken link in README.
* Fix broken link in README.
... by replacing it with a group of badges referring to the status of the GH Actions workflows.
* Check the badges at the top of the README display and link to the correct place.

README: fix broken build status badge

---

.github/workflows/test.yml
.gitignore
README.md
phpunit.xml.dist

* Identify areas with too few tests
* Enable test code coverage monitoring.
This commit makes the necessary changes to start recording and uploading code coverage data to Coveralls.
Includes:
* Updating the GH Actions `test` workflow to run the high/low PHP version builds with code coverage and upload the results.
* Updating the PHPUnit config to show an inline code coverage summary and improve the `filter` configuration.
* Ignoring the potentially generated code coverage files in the `build/*` directory to prevent it being committed.
* Adding a code coverage badge to the README.
Not included as already in place:
* Adding a script to the `composer.json` file to run code coverage.
Notes:
* Coverage will be recorded using `Xdebug` …

CI/QA: start recording code coverage

---

.github/workflows/cs.yml
.github/workflows/lint.yml
.github/workflows/test.yml

* CI maintenance
* CI maintenance
Only run the workflows when there is a chance that the result of the workflow run will be different from before.
The path selection is set up to cast a wide net to make the risk of the workflows not running when the build could potentially break as small as possible.
This means that, aside from files of the type being checked in the workflow changing, the workflow will also run when:
* The configuration used changes.
* Dependencies used in the workflow may potentially have changed.
* Composer scripts used in the workflow may potentially have changed.
* Shell scripts used in the workflow have changed.
* The workflow itself changes.
* Miscellaneous related files have changed.
Note: the lists of …

GH Actions: run workflows more selectively

---

duplicate-post.php
src/admin/views/options.php
src/ui/row-actions.php
src/utils.php

* Improve translator context by adding a `Hidden accessibility text.` comment whenever translations are _only_ used in either screen reader texts or aria labels. To be clear: this means searching for the same translation in the same text domain, if it is used in any other context than screen reader/aria label that means no comment should be there. This is due comments appearing above _all_ the references.
* Adds mark above translations that are used only for screen readers.
* It would be nice to have a search yourself, to see if I missed any instances?
* Note that I intentionally ignored where the variable was used in more than just the screen reader, or in apps, or deprecated. Or when the same translation was used in a non …

Mark translations that are only for screen readers

---

composer.json

* Users requiring this package via [WP]Packagist can now use the `composer/installers` v2.
* Users requiring this package via [WP]Packagist can now use the `composer/installers` v2.
While the latest version of the `composer/installers` package is `2.2`, I'm explicitly setting the version constraint to a lenient one as this is a non-`dev` requirement, which comes into play when people use a [WP]Packagist based site setup.
If we set the requirement very strictly, it could conflict with other plugins with different constraints and it is not as if any of the 2.x releases have touched the WordPress installer, so setting it to `|| 2.0` should be fine.
* _N/A_

Composer: allow composer installers 2.x

---

composer.json
tests/unit/bootstrap.php

* Updated test dependencies
* Updated test dependencies
This updates the minimum version of the WP Test Utils dependency.
This also allows us to remove the work-around which was in place for Mockery not handling dynamic properties on mocked objects. This was fixed in Mockery 1.6.0, which will be used when running the tests against PHP 8.2+.
Note: PHPUnit Polyfills 1.1.0 includes a new polyfill for the `assertObject[Not]HasProperty()` methods. The assertions which these new assertions replace are not used in this test suite, so no test changes are needed.

Composer/Tests: update test dependencies

---

.github/workflows/test.yml
composer.json
phpunit-wp.xml.dist

* Improve consistency in terminology used.
* Improve consistency in terminology used.
Related to/follow up on #313
The "integration" tests are being renamed to "WP (unit) tests".
This commit updates the references to these tests in the Composer scripts and the GH Actions workflows to follow the new terminology.
Note: the "old" `integration-test` and `integration-coverage` Composer scripts will still be available for the time being to facilitate the switch over and give the teams a little time to get used to the new script names.
* Check if the GH actions builds run correctly
* Check if code coverage is correctly uploaded and recorded.
* Locally check the new scripts (and …

Tests: consistency in terminology

---

composer.json

* Tidy up `composer.json` file and improve usability of scripts
* Tidy up `composer.json` file and improve usability of scripts
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
These descriptions will be used when a list of the available scripts is requested on the command-line using the `composer list` or `composer run -l` commands.
These descriptions also help document the different scripts for the maintainers of the `composer.json` file.
Ref: …

Composer: normalize the file, add script descriptions

---

tests/Unit/Admin/Options_Form_Generator_Test.php
tests/Unit/Permissions_Helper_Test.php
tests/Unit/Post_Duplicator_Test.php
tests/Unit/Post_Republisher_Test.php
tests/Unit/UI/Block_Editor_Test.php
tests/Unit/Utils_Test.php

*
* Tests: use static dataproviders
As of PHPUnit 10, data providers are (again) expected to be `static` methods.
This updates the test suite to respect that.
* _N/A_ If the builds pass, we're good.

Tests: make dataproviders `static`

---

admin-functions.php
src/ui/column.php
src/ui/newsletter.php

*
* Range of small bug fixes
The `Column::quick_edit_remove_original()` method only expects one parameter, so no need to ask WP for 2.
The `wp_nonce_field()` function by default _displays_ the field.
This means that, as things were, the nonce field would be echo'd out when the function was called + would add a `1` to the `$html` string being created.
The resulting `$html` string would not contain the nonce field and the nonce field would not be between the `<form>` tags.
Fixed by setting the `$display` parameter to `false`.
Ref: https://developer.wordpress.org/reference/functions/wp_nonce_field/
The `explode()` function will always return an array, so strict comparing the return value with an empty string will never result in a …

Various small bug fixes

---

.github/workflows/cs.yml
.github/workflows/lint.yml
composer.json
config/composer/actions.php

* CI/Composer scripts improvement
* CI/Composer scripts improvement
This adds a number of extra CS-related Composer scripts and handler functions.
This:
* Uses the same menu as is already in use in the Free, Premium and several other plugins for predictability.
* Where necessary, adjusts existing Composer scripts to, again, be in line with what is already in use in Free and Premium.
This also adds the _ability_ to run CS with a Threshold. As the codebase is currently clean, this ability is not activated for CI for the time being, though it is likely that it will be activated once YoastCS 3.0 will be used.
Note: this change does mean that, in contrast to before, running `check-cs` will now return only errors. While this is new for …

Composer: implement CS menu and extra commands

---

src/handlers/check-changes-handler.php
src/ui/column.php

CS/QA: use `printf()`, not `echo sprintf()`

---

admin-functions.php

CS/QA: use import `use` statements

---

.github/workflows/cs.yml
.phpcs.xml.dist
composer.json

* CI/QA update introducing YoastCS 3.0
* CI/QA update introducing YoastCS 3.0
YoastCS 3.0.0 has been released and is based on WordPressCS 3.0.0.
This commit makes the necessary updates for that:
* Composer: update the requirements.
* PHPCS ruleset:
- Update a few sniff/property names for new names in WordPressCS 3.0.
- Enforce strict PSR-4 for the tests.
- Add configuration for the new `WordPress.WP.Capabilities` sniff.
- Remove a few exclusions which are no longer needed.
- Add a few selective exclusions for specific situations.
* GHA CS workflow: run the CS check on the latest PHP version.
No need to run on PHP 7.4 any more as the deprecations previously encountered were all fixed.
Refs:
* …

Composer/PHPCS: update to YoastCS 3.0.0

---

composer.json
js/src/duplicate-post-edit-script.js
src/watchers/copied-post-watcher.php
src/watchers/link-actions-watcher.php
src/watchers/original-post-watcher.php
src/watchers/republished-post-watcher.php
tests/Unit/Watchers/Copied_Post_Watcher_Test.php
tests/Unit/Watchers/Link_Actions_Watcher_Test.php
tests/Unit/Watchers/Original_Post_Watcher_Test.php
tests/Unit/Watchers/Republished_Post_Watcher_Test.php

*
* Fixes a bug where notices would not be appearing in the block editor, throwing console errors, with some locales.
*
* use the latest released version (or `main`)
* switch WP to Italian, this ensures that the translated string has an `'` which breaks the parsing
* keep the console open
* create a Rewrite & Republish copy of a published post
* see that when you are redirected to the Editor you don't see any notice
* see that you get a JS error in the console: `Uncaught ReferenceError: duplicatePostNotices is not defined`
* switch to this branch 
* switch WP to Italian, this ensures that the translated string has an `'`
* keep the console open
* create a Rewrite & …

Fix notices errors with some locales

---

admin-functions.php

Cloning a post can cause a critical error due to the type of `get_option( 'duplicate_post_taxonomies_blacklist' )` which can be a `NULL` value.
Related Issues:
1. https://wordpress.org/support/topic/taxonomies-are-not-copied-because-duplicate_post_taxonomies_blacklist-is-null/
2. https://github.com/Yoast/duplicate-post/issues/263
* Fix `duplicate_post_taxonomies_blacklist` option causing cloning errors due to inconsistent output type (array, empty string, null)
* Fixes a bug where a fatal error could be thrown when cloning a post because of a wrong type for the `duplicate_post_taxonomies_blacklist` option. Props to @michael-sumner.
* I added some more checks, reprising some unfinished work that never made it to a PR:
*  covering …

Fix Possible NULL Value of `duplicate_post_taxonomies_blacklist`

---

.github/workflows/cs.yml
composer.json
config/composer/actions.php
src/watchers/link-actions-watcher.php

* Update dev dependencies
* Update dev dependencies
Nearly all dev dependencies have had new releases. This commit updates the plugin to use the new versions.
For linting, the upgrade will get us preliminary PHP 8.4 support.
For CS, the upgrades will get us improved syntax support for PHP 8.3, more documentation and a range of bug fixes.
This changes the implementation of the coding standards threshold check to require that both the `YOASTCS_THRESHOLD_ERRORS` environment variable, as well as the `YOASTCS_THRESHOLD_WARNINGS` environment variable match the current status exactly.
This prevents PR A fixing some issues and forgetting to update the threshold, which then would allow PR B to introduce new issues.
This PR can be …

Composer: update dev dependencies

---

duplicate-post.php

The plugin was loading translations too early on `plugins_loaded`. Plugins should wait until `init` to ensure the current user has been set up, so that the current user's locale can be respected.
That said, why manually load translations when WordPress can do it for you :-)
* Improves how the translations are loaded by relying on the WordPress mechanism for that. Props to @swissspidy.
* See above
* Set a language which has 100% of the translations (see the [list](https://translate.wordpress.org/projects/wp-plugins/duplicate-post/))
* visit Settings > Duplicate Post and check that all the strings are translated
* visit the Post list and check that the row actions, the bulk …

Rely on just-in-time translation loading

---

admin-functions.php

* fix a typo for child pages post excerpt.
See Reports https://wordpress.org/support/topic/excerpt-problem-9/ and #369
Fixes #369
* Fixes a bug where cloning an attachment did not copy its description as expected.
* Fixes a bug where cloning an attachment did not copy its caption as expected. Props to @masteradhoc.
* -
* in the Duplicate Post settings, under "Post/page elements to copy", select "Attachments" and save
* Create/edit a post
* add an image to it *by uploading a new one* 
* make sure to edit the image in the media library modal and add alt. text, caption and decription.
* save the post
* clone the post
* check the media library page: you should get 2 copies of …

fix post excerpt typo

---

.github/workflows/test.yml

* Ubuntu latest 24.0 does not contain SVN, so we manually add a step to the wp-test workflow to install SVN.
* Update testing workflow to install SVN
*
*
*
*
Fixes #

Adding step in wp-test flow to install SVN

---

config/scripts/install-wp-tests.sh

* Update test tooling
* Update test tooling
The upstream `install-wp-tests.sh` script has been updated. This commit incorporates the upstream changes in the local copy used in this repo.
Refs:
* wp-cli/scaffold-command#345
* _N/A_ If the build runs & passes, we're good.

WP Tests: update install WP script

---

.github/workflows/test.yml

* CI improvement
* CI improvement
PR #380 dropped support for WP < 6.4, but the integration test matrix had not been updated to reflect this change.
Fixed now.
* _N/A_ If the build runs & passes, we're good.

GH Actions/tests: fix up the matrix

---

.github/workflows/lint.yml
.github/workflows/test.yml

* Test against PHP 8.4
* Test against PHP 8.4
* As the PHP 8.4 builds pass and the PHP 8.4 release has been out for a few months, the builds are not _allowed to fail_.
* Update PHP version on which code coverage is run (high should now be 8.4).

GH Actions: enable linting and testing against PHP 8.4

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
composer.json
duplicate-post.php
readme.txt

* We want to drop PHP 7.2 and 7.3 compatibility.
* Drops compatibility with PHP 7.2 and 7.3.
* N/A
* Follow the exact same test instructions in [this](https://github.com/Yoast/wordpress-seo/pull/22077) PR.
* N/A
Fixes [#401](https://github.com/Yoast/duplicate-post/issues/401)

Drop support for Php 7.2 and 7.3

---

js/src/duplicate-post-strings.js
js/src/helpers/safe-create-interpolate-element.js

*
* Adds safety check to avoid breaking errors due to wrong tags order in translation.
*
* When building the plugin, make sure you are on node 16.
* Go to posts or pages
* Hover over a post and click on `Rewrite and Republish`.
* Edit that new post and change the publish date to something in the future and click on `Schedule Republish`
* Check you see the message:
> You're about to replace the original with this rewritten post at the specified date and time.
*
*
Fixes [Add and implement safeCreateInterpolateElement in duplicate-post …

use safeCreateInterpolateElement

---

.github/dependabot.yml

* Prevent annoying comments on PRs
* Update Dependabot config
Support for the `reviewers` key in `dependabot.yml` files is being removed by GitHub on May 20th 2025.
The recommendation is to have a `CODEOWNERS` file to set reviewers instead.
For now, this commit removes the `reviewers` key from the `dependabot.yml` file without replacing it. That should prevent comments being left in PRs by the dependabot bot account about the field no longer being supported.
Ref:
* https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-loca …

Dependabot: remove reviewers
